[Aleo ins.] Add branching commands
AleoHQ/grammars pull request #42
Opened 2023-06-01 17:58 UTC by acoglio

2023-06-01 19:32 UTC, HarukaMa commented
Are we going to be Turing complete with this? I thought it would be pretty hard to achieve this, but this opcode really just looks like a general conditional branching instruction.

2023-06-01 19:42 UTC, acoglio commented
The current plan is to have post-parsing restrictions that only allow forward branching, ensuring termination. Also note that this is only allowed in finalizers that run on-chain, so it doesn't get compiled to an arithmetic circuit.

2023-06-15 06:32 UTC, bendyarm approved these changes

2023-06-22 16:49 UTC, d0cd requested changes

2023-06-22 16:49 UTC, d0cd commented on aleo.abnf
> +command = get / get-or-init / set / branch / instruction
```suggestion
command = get / get-or-init / set / branch / instruction / position
```

2023-06-22 21:59 UTC, merged