[Aleo ins.] Update cast instructions.
AleoHQ/grammars pull request #47
Opened 2023-06-16 06:34 UTC by acoglio

Matches:
- https://github.com/AleoHQ/snarkVM/pull/1673
- https://github.com/AleoHQ/snarkVM/pull/1665

The snarkVM use 'cast type' for the thing that is either a register type or `group.x` or `group.y`. In the grammar I use `cast-destination` instead, because `group.x` and `group.y` are not quite types.

2023-06-21 16:18 UTC, bendyarm approved these changes

2023-06-22 16:46 UTC, d0cd requested changes

2023-06-22 16:46 UTC, d0cd commented on aleo.abnf
> +cast-op = %s"cast" / %s"cast.lossy"
```suggestion
cast-op = %s"cast"
```

2023-06-22 22:10 UTC, d0cd approved these changes
LGTM!

2023-06-22 22:12 UTC, merged