[Leo] Add support for underscores in numeric literals
AleoHQ/grammars pull request #51
Opened 2023-08-18 23:25 UTC by evan-schott

As detailed in [Leo PR](https://github.com/AleoHQ/leo/issues/2538) want to allow numbers like `1_000_000u32` to exist. This is similar to the [Aleo grammar](https://github.com/AleoHQ/grammars/blob/1e3c08275395f1afb733dde78aaddd727eeebbcd/aleo.abnf#L177C1-L177C1) and [Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=554372f372214b10c2d4bc8783d194c0).

2023-08-19 17:26 UTC, acoglio approved these changes

2023-08-25 18:21 UTC, acoglio commented on leo.abnf
> +whole-number = %x30 / ( %x31-39 *( decimal-digit ) )
```suggestion
tuple-index = "0" / nonzero-decimal-digit *( decimal-digit )
```
where the following should be also added just after `decimal-digit = ...`:
```
nonzero-decimal-digit = %x31-39
```

2023-08-25 18:21 UTC, acoglio commented on leo.abnf
> +tuple-component-expression = postfix-expression "." whole-number
```suggestion
tuple-component-expression = postfix-expression "." tuple-index
```

2023-08-25 18:25 UTC, acoglio requested changes
Thanks, it looks structurally good!

My suggestions are just terminological nitpicking (can't help it): 'whole number' generally refers to natural or integer numbers (https://en.wikipedia.org/wiki/Whole_number) and what we define are really sorts of 'numerals' (https://en.wikipedia.org/wiki/Numeral) — numerals are "syntax", numbers are "semantics".

I also slightly shortened a rule: in ABNF, `%x30` is equivalent to `"0"`, and the `( ... )` around the alternative are unnecessary because `/` binds less tightly than sequencing.

2023-08-25 21:32 UTC, evan-schott commented
Ok sounds good! I just added a nonzero-decimal-digit definition since it didn't look like there was one yet

2023-08-25 23:02 UTC, acoglio approved these changes

2023-08-25 23:03 UTC, merged